[package]
name = "astroport-circular-buffer"
version = "0.2.0"
edition = "2021"
authors = ["Timofei Epanchintsev <5527315+epanchee@users.noreply.github.com>", "Astroport"]
description = "Circular buffer to store time series data in CosmWasm contracts"
license = "Apache-2.0"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

[dependencies]
cw-storage-plus.workspace = true
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
thiserror.workspace = true